### ISSUE TITLE
maze generator biased?

### ISSUE THREAD

**Issue by GuidoJansen** [diowa/amazed#1]
I think the generator is not symmetrical.
If I try to solve the 10x10 maze on your demo page https://diowa-amazed.herokuapp.com/ I somehow felt that when I start at [9,9] point the mazes are more difficult to solve than when I start from [1,1]

From top left it seems that the path until one reaches the first branch is longer than from the bottom right

**Comment by GuidoJansen** [comment]
yellow and turquoise: pathes to the first branch
green circles: branch tiles.

![image](https://cloud.githubusercontent.com/assets/3098067/11473189/6f3191f6-9771-11e5-973e-8537d502cd80.png)

![image](https://cloud.githubusercontent.com/assets/3098067/11473146/351752ee-9771-11e5-8938-5accfe1a8376.png)

**Comment by GuidoJansen** [comment]
An [0,0] seems to be a dead end always.

**Comment by cesidio** [comment]
Hello Guido,

Yes the recursive backtracker algorithm has a tendency toward long and winding passages with relatively fewer dead-ends than other algorithms.

This presentation is enlightening on that regard:
http://www.jamisbuck.org/presentations/rubyconf2011
